sudo: false
language: scala

scala_version_211: &scala_version_211 2.11.12
scala_version_212: &scala_version_212 2.12.8
scala_version_213: &scala_version_213 2.13.0-M5

java11: &java_11 openjdk11
java12: &java_12 openjdk12

stages:
  - name: test
  - name: publish
    if: (branch = master AND type = push)

jobs:
  include:
    - &tests
      env: TEST="test"
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test
        - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues
      scala: *scala_version_211
      jdk: *java_11
    - <<: *tests
      scala: *scala_version_212
    - <<: *tests
      scala: *scala_version_213
    - <<: *tests
      scala: *scala_version_212
      jdk: *java_12

    - env: TEST="docs"
      before_install:
        - export PATH=${PATH}:./vendor/bundle
      install:
        - rvm use 2.6.0 --install --fuzzy
        - gem update --system
        - gem install sass
        - gem install jekyll -v 3.2.1
      script: sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite
      scala: *scala_version_212

    - &publish
      stage: publish
      env: TEST="publish"
      scala: *scala_version_211
      jdk: *java_11
      script:
        - sbt ++$TRAVIS_SCALA_VERSION publish
    - <<: *publish
      scala: *scala_version_212
    - <<: *publish
      scala: *scala_version_213
      
    - env: TEST="publish docs"
      scala: *scala_version_212
      jdk: *java_11
      script:
        - sbt ++$TRAVIS_SCALA_VERSION docs/publishMicrosite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
