dist: xenial
sudo: false
language: scala

scala_version_211: &scala_version_211 2.11.12
scala_version_212: &scala_version_212 2.12.8
scala_version_213: &scala_version_213 2.13.0-M5
scala_version_docs: &scala_version_docs 2.12.8
  
java11: &java_11 openjdk11
java12: &java_12 openjdk12

stages:
  - name: test
  - name: publish
    if: (branch = master AND type = push)

jobs:
  include:
    - &tests
      env: TEST="test"
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test
        - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues
        - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll        
      scala: *scala_version_211
      jdk: *java_11
    - <<: *tests
      scala: *scala_version_212
    - <<: *tests
      scala: *scala_version_213
    - <<: *tests
      scala: *scala_version_212
      jdk: *java_12

    - env: TEST="docs"
      scala: *scala_version_docs
      script:
        - sbt ++$TRAVIS_SCALA_VERSION docs/makeSite

    - &publish
      stage: publish
      env: TEST="publish"
      jdk: *java_11
      scala: *scala_version_docs
      before_script:
        - echo $PGP_SECRET | base64 --decode | gpg --import
      script:
        - sbt ++$TRAVIS_SCALA_VERSION +publishSigned docs/makeSite docs/ghpagesPushSite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
